version: '3.8'

services:
  frontend:
    build:
      context: ./f-resume-screener
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://92.113.147.146:5000
    depends_on:
      - backend

  backend:
    build:
      context: ./b-resume-screener
      dockerfile: Dockerfile
    ports:
      - "92.113.147.146:5000:5000"
    environment:
      - PORT=5000
      - REDIS_URL=redis://redis:6379
      - CORS_ORIGIN=http://92.113.147.146:3000
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

volumes:
  redis_data:
